### ISSUE TITLE
Change the appearence of the Digital clock Project

### ISSUE THREAD

**Issue by Bhuvanchand26** [TusharKesarwani/Front-End-Projects#1039]
I will change the entire frontend of the Digital Clock project. I will also put a 24 hour clock on the project page.

![Screenshot (499)](https://github.com/TusharKesarwani/Front-End-Projects/assets/131843589/e96a41b9-b8f1-485c-9b4a-18b6e9e1e9ec)

Assign me this issue @TusharKesarwani 
I can solve this!
I'm a SSOC contributor

**Comment by khushi-shrama** [comment]
Hi @TusharKesarwani 

I'd like to contribute to this project and I'm interested in working on the issue. I believe I can add value to this problem because I have relevant knowledge of front-end development. If possible, could you assign this issue to me?
 I'm excited to collaborate with the team and make progress on it.

Thank you for your consideration!
