### ISSUE TITLE
Improving the readme file of this project 

### ISSUE THREAD

**Issue by harshsingh32** [TusharKesarwani/Front-End-Projects#732]
I would like to work on improving the readme file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under SSoC'23.

**Comment by chaitanyarai19** [comment]
Hello, I am reaching out as a participant of the SSoC'23 program with a request to assign an issue in GitHub for the purpose of improving the README file of our project. Please consider me for assigning this issue because I have experience in technical writing, project documentation, and familiarity with the project's codebase.

**Comment by manasvipriya** [comment]
Hey @TusharKesarwani ,
I would love to contribute in your project and improve your README file of your project.

**Comment by arpy8** [comment]
I would like to contribute !

**Comment by TusharKesarwani** [comment]
Create a fresh issue after 1st June
