### ISSUE TITLE
Contact Page in Front End Projects website (Ssoc'23)

### ISSUE THREAD

**Issue by kadambari68** [TusharKesarwani/Front-End-Projects#815]
I suggest making a contact page for your website so that people can connect to you and get their problems resolved quickly.
The page can contain your professional email address, LinkedIn profile, Github profile, and contact no. (if you want) and any other website you wish.

Also, you can ask them to write their feedback, suggestions, or any kind of comment on the website which will get stored in the database which you can review later. 

For the first point, only HTML CSS javascript(or reactjs but not needed) would be required but for the second one, we would also need to create a PHP file and a database to store the comments. 

I can do all of this please tell me your thoughts(Ssoc'23)

**Comment by Chandana-756** [comment]
I think making a contact page is a good idea so that if they have any suggestions or any issues they can contact you and get solved it as early as possible. This page should contain your contact details like name, email id , contact number, your social media account profile ids like facebook, whatsapp, linkedin, github and any other details if you wish can be provided.  

You can provide feedback column so that if they have any issues or any suggestions they can type in that column. 
We can do this by using html, css , javascript and php. 

I can able to do all of these things. Let me know your thoughts(Ssoc `23)

**Comment by Shu12388y** [comment]
@kadambari68 @Chandana-756 @TusharKesarwani can you assign this issue to me i want to work on this issue
