### ISSUE TITLE
Adding Footer and Login/Sign up Page in "Villa Hotel Website" Project

### ISSUE THREAD

**Issue by KritikaRawat** [TusharKesarwani/Front-End-Projects#867]
Problem : 
Without Login/Signup, we can't track the user which leads to poor communication and personalized experience. And without the footer, the website seems to be incomplete.
 
**Solution**
The solution I will provide is to add a good login/Signup page and add the footer.

**Comment by Shraddha16092002** [comment]
I want to work over this issue. please assign it to me.

**Comment by Yash493** [comment]
I want to work over this issue. please assign it to me.

**Comment by kundu-baivab** [comment]
Hello,
Is your feature request related to a problem? Please describe.
=> I will add an innovative login and sign up page to this website, so that all the users records are kept, and no unknown actions in the website goes unnoticed. It would also add to the security of the website, and also add to its UI.

Login/Register functionality:
https://github.com/TusharKesarwani/Front-End-Projects/assets/106022593/7fa5c918-d8c9-4389-bb4d-06c3c48fa568

I would also add a footer to the website in order to level up the UI of the website, so that it becomes more interactive and attract more users, and I would also add readily required information regarding the site like contact number and all on the footer, to make the users more comfortable while surfing through the website.


Describe the solution you'd like.
=> I would implement all the changes that I mentioned above using the fundamental languages of web development which include HTML5, CSS3 and Javascript.


Please assign this issue to me under SSoC Season 2

**Comment by Gyanthakur** [comment]
assign me this issue.
